export const RUNTIME_WS_BROADCAST_BUS = Symbol("RUNTIME_WS_BROADCAST_BUS");
export const RUNTIME_WS_INSTANCE_ID = Symbol("RUNTIME_WS_INSTANCE_ID");
export const RUNTIME_WS_REPLAY_STORE = Symbol("RUNTIME_WS_REPLAY_STORE");
